name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install dev dependencies
        run: npm install -D tailwindcss postcss autoprefixer

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Prepare for deployment
        run: |
          touch ./dist/.nojekyll
          cp -r ./dist/* ./out/
          touch ./out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: ${{ secrets.CNAME }} 